// <auto-generated />
using System;
using FaG.Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaG.Data.Migrations
{
    [DbContext(typeof(FaGDbContext))]
    [Migration("20260322090734_AddInsertedDate")]
    partial class AddInsertedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaG.Data.DAL.FearGreedIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NegativePosts")
                        .HasColumnType("integer");

                    b.Property<int>("NeutralPosts")
                        .HasColumnType("integer");

                    b.Property<int>("PositivePosts")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreInt")
                        .HasColumnType("integer");

                    b.Property<double>("ScoreNormalized")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalPosts")
                        .HasColumnType("integer");

                    b.Property<int>("UnratedPosts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FearGreedIndices");
                });

            modelBuilder.Entity("FaG.Data.DAL.UserPostEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Emotion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReactionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalReactions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPostEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
