// <auto-generated />
using System;
using FaG.Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaG.Data.Migrations
{
    [DbContext(typeof(FaGDbContext))]
    [Migration("20260405143415_Add imoex table")]
    partial class Addimoextable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaG.Data.DAL.FearGreedIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<double>("CumulativeIndex")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("InertialCumulative")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NegativePosts")
                        .HasColumnType("integer");

                    b.Property<int>("NeutralPosts")
                        .HasColumnType("integer");

                    b.Property<double>("NeutralRatio")
                        .HasColumnType("double precision");

                    b.Property<double>("NormalizedCumulative")
                        .HasColumnType("double precision");

                    b.Property<int>("PositivePosts")
                        .HasColumnType("integer");

                    b.Property<double>("RawIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("SmoothedIndex")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalRelevantPosts")
                        .HasColumnType("integer");

                    b.Property<int>("UnratedPosts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FearGreedIndices");
                });

            modelBuilder.Entity("FaG.Data.DAL.IMOEXIndexTradeDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("High")
                        .HasColumnType("double precision");

                    b.Property<double>("Low")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnType("double precision");

                    b.Property<double>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IMOEX");
                });

            modelBuilder.Entity("FaG.Data.DAL.PostEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Emotion")
                        .HasColumnType("integer");

                    b.Property<string>("Evaluator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Longiness")
                        .HasColumnType("bigint");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostEvaluations");
                });

            modelBuilder.Entity("FaG.Data.DAL.UserPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorNickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Lenght")
                        .HasColumnType("integer");

                    b.Property<string>("ReactionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalReactions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPosts");
                });

            modelBuilder.Entity("FaG.Data.DAL.PostEvaluation", b =>
                {
                    b.HasOne("FaG.Data.DAL.UserPost", "Post")
                        .WithMany("Evaluations")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FaG.Data.DAL.UserPost", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
